-- AI FUNCTIONS
--
-- INIT_ai() -- This needs to be run at Map initialization as a custom script
--
-----------
-- FUNCTIONS
--  * means optional variable
--
--  Add new things to the fold
--  [X] ai.addTown(name, hostileForce)                                          -- Adds a new town to the map.  (NEEDS to be extended with additional RECTs)
--  [X] ai.addLandmark(town, name, rect, {types}, *unit, *radius, *maxCapacity) -- Sets up a new landmark in a town that will be used by Units
--  [X] ai.addUnit(town, type, name, unit, shift*)                              -- Adds a unit that exists into the fold to be controlled by the AI. Defaults to Day shift.
--  [X] ai.addRoute(name)                                                       -- Adds a route that villagers can take when moving
--
--  Extend Town Size
--  [X] ai.extendTown(name, rect)                                               -- Adds an additional RECT to a town that already exists

--  Route Actions
--  [X] ai.routeAddStep(rect, time*, lookAtRect*, animation*, speed*)            -- Adds at the end of the selected route, a new place for a unit to move to.
--  [X] ai.routeAddOption(route, step, rect, time, lookAtRect, animation, speed) -- Adds an additional option to the picked route step
--  [X] ai.routeGetStepCount(route)
--  [X] ai.routeGetOptionCount(route, step)
--
--  Town Actions
--  [X] ai.townState(name, state)                        -- Changes the town state to the specified state
--  [X] ai.townHostileForce(name, force)                 -- Changes the allegience of the town and all of the units to the new force.
--  [X] ai.townVulnerableUnits(name, [True, False])      -- Sets all units of a town to be vulnerable / invulnerable.
--  [X] ai.townVulnerableLandmarks(name, [True, False])  -- Sets all landmarks of a town to be vulnerable / invulnerable.
--  [X] ai.townUnitsHurt(name, low, high, kill)          -- Damages all units of the town by a random percentage from low to high.
--  [X] ai.townUnitsSetLife(town, low, high)             -- Sets all units of a town to a percent life in a random number within the low and high.
--  [ ] ai.townHurtLandmarks(name, low, high)            -- Damages all landmarks of the town by a random percentage from low to high.
--  [ ] ai.townAddUnits(name, amount, unitType)          -- Adds additional units of unit type to the town and places them at a random residence.
--  [ ] ai.townPause(town, [True, False])                -- Pauses / Unpauses all Units and Landmarks in a town.
--
--  Landmark Actions
--  [ ] ai.landmarkState(rect, state)           -- Changes the landmark state to the specified state
--  [ ] ai.landmarkKill(rect)                   -- Kills the landmark, displacing any Units connected to it.
--
--  Unit Actions
--  [ ] ai.unitState(unit, state)               -- Changes the unit state to the specified state
--  [ ] ai.unitAddRoute(unit, route)            -- Adds the picked route to one of the units routes
--  [ ] ai.unitChangeHome(unit, rect)           -- Changes the unit's home position to the center of the selected rect.
--  [ ] ai.unitKill(unit)                       -- Kills the unit and removes all references from AI.
--  [ ] ai.unitPause(unit, flag)                -- Puases a unit.  Pauses the unit and all updating.
--
--  Set Unit Types
--  [ ] ai.unitVillager(unit)                   -- Set unit as a Villager
--  [ ] ai.unitMilitia(unit, unitTypeTransform) -- Set unit as a Militia
--  [ ] ai.unitTraveler(unit)                   -- Set unit as a Soldier
--  [ ] ai.unitFollower(unit, unitFollowing)    -- Set unit as a Follower, also need to specify the unit to follow.
--  [ ] ai.unitChild(unit)                      -- Set unit as a Child
--  [ ] ai.unitCustom(unit, {states})           -- Set unit as a custom type.  Will take on the states selected.
--
-----------
-- STATES
--
--  Town States
--  [ ] auto        -- The town will automatically choose what state it should be in.
--  [ ] normal      -- *AUTO* The town is reporting everything is fine.
--  [ ] danger      -- *AUTO* The town is reporting that it is in danger.
--  [ ] pause       -- The town will tell all of it's residences to pause and wait.
--  [ ] gather      -- The town is reporting that everyone needs to gather in the town center
--  [ ] abandon     -- The town is reporting that everyone should Abandon the Town.
--
--  Landmark States
--  [ ] auto        -- The Landmark will automatically choose what state to be in.
--  [ ] normal      -- *AUTO* The Landmark is not reporting anything wierd.
--  [ ] danger      -- *AUTO* The Landmark is reporting danger
--  [ ] off         -- The Landmark is turned off and won't influence any behavior.
--
--  Unit States Available
--  [ ] auto        -- Unit will automatically choose what state to be in.
--  [ ] relax       -- Unit will stay where it's at and maybe run some specific animations.
--  [ ] move        -- Unit will move around to a different spot inside it's current town.
--  [ ] travel      -- Unit will travel to a new town.
--  [ ] gather      -- Unit will move to the Town gathering spot, pick a random spot to stand in.
--  [ ] sleep       -- Unit will look for a residence to sleep in for the night.
--  [ ] play        -- Unit will go to a designated "play" area and run through pre-assigned routes / things.
--  [ ] patrol      -- Unit will patrol around the town.  Looking for enemies to attack during his shift.
--  [ ] defend      -- Unit will defend the town until all threats have been eliminated.
--  [ ] guard       -- Unit will stand in a position and will guard it always during his shift.
--  [ ] attack      -- Unit will attack the specified town.
--  [ ] follow      -- Unit will follow it's attached unit
--  [ ] flee        -- Unit will try to run away. (Either to nearest safehouse, or will keep running to landmarks in town if no safehouses)
--  [ ] arm         -- Unit will try to find a barracks and arm himself to fight.
--
--
--
-----------
-- TYPES
--
--  Landmark Types (Each landmark can be multiple types)
--  [ ] residence   -- This landmark will allow Units to sleep in it.
--  [ ] safehouse   -- This landmark will allow Units to Hide in it when Fleeing from Danger.
--  [ ] barracks    -- This landmark can house soldiers to be deployed if the town is under attack.
--  [ ] gathering   -- This landmark is used to gather get the Units to gather together.
--
--  Route Types (Each route can only be one type)
--  [ ] inTown      -- This route will take units to other points in it's town.
--  [ ] outOfTown   -- This route will take a unit to a new town.
--
--  Unit Types (Each unit can only be one type at a time)
--  [X] villager    -- Ordinary villager.  Will go about business, will always run away, and never fight.  Slows down when hurt, won't leave town.
--          {relax, move, gather, sleep, flee}
--
--  [ ] militia     -- Appears as an ordinary villager but if town is in danger and contains a barracks, go to it and transform into a milita and fight.
--          {relax, move, gather, sleep, arm}
--
--  [ ] soldier     -- protects the town, never leaves the town unless told to attack another town.  Will always fight when under attack.
--          {relax, move, gather, sleep, guard, patrol, defend, attack}
--
--  [ ] traveler    -- Will go about business, will always run away, and never fight.  Slows down when hurt, will travel to other towns.
--          {relax, move, sleep, travel}
--
--  [ ] follower    -- Will always follow it's lead unit. (Good for pack mules, that type of thing)  If lead unit dies, will flee to it's town and become a villager.
--          {follow}
--
--  [ ] child       -- Will play during the day, or sight see.
--          {move, sleep, play}
--
--  [ ] custom      -- No states will be added to this unit.  Will need to manually set up what unit will do.
--
--
-----------
-- SHIFTS
--
--  [ ] day     -- Units will be awake and active during the day.
--  [ ] night   -- Units will be awake and active during the night.
--  [ ] all     -- Units will be awake and active always.
