-- AI FUNCTIONS
--
-- INIT_ai() -- This needs to be run at Map initialization as a custom script
--
-----------
-- FUNCTIONS
--  * means optional variable
--
--  Add new things to the fold
--  [A] ai.town.new(name, hostileForce)                                          -- Adds a new town to the map.  (NEEDS to be extended with additional RECTs)
--  [X] ai.landmark.new(town, name, rect, {types}, *unit, *radius, *maxCapacity) -- Sets up a new landmark in a town that will be used by Units
--  [A] ai.unit.new(town, type, name, unit, shift*)                              -- Adds a unit that exists into the fold to be controlled by the AI. Defaults to Day shift.
--  [A] ai.route.new(name)                                                       -- Adds a route that villagers can take when moving

--  Extend Town Size
--  [X] ai.town.extend(name, rect)                                               -- Adds an additional RECT to a town that already exists

--  Route Actions
--  [A] ai.route.step(route, rect, time, speed*, walk?*)     -- Adds at the end of the selected route, a new place for a unit to move to.
--  [X] ai.route.action(route, time, lookAtRect*, animation*, loop?*)                          -- Adds an additional option to the picked route step
--  [ ] ai.route.trigger(route, trigger)
--  [ ] ai.route.function(route, function)
--  [ ] ai.route.branch(route, {newRoutes})                                           -- Adds a branch at the end of a route to pick a random new route from list of routes to send a unit to.                               

--  [X] ai.route.stepCount(route)
--  [X] ai.route.actionCount(route, step)

--  Town Actions
--  [X] ai.town.state(name, state)                        -- Changes the town state to the specified state
--  [X] ai.town.hostileForce(name, force)                 -- Changes the allegience of the town and all of the units to the new force.
--  [A] ai.town.vulnerableUnits(name, [True, False])      -- Sets all units of a town to be vulnerable / invulnerable.
--  [X] ai.town.vulnerableLandmarks(name, [True, False])  -- Sets all landmarks of a town to be vulnerable / invulnerable.
--  [X] ai.town.unitsHurt(name, low, high, kill)          -- Damages all units of the town by a random percentage from low to high.
--  [X] ai.town.unitsSetLife(town, low, high)             -- Sets all units of a town to a percent life in a random number within the low and high.
--  [ ] ai.town.hurtLandmarks(name, low, high)            -- Damages all landmarks of the town by a random percentage from low to high.
--  [ ] ai.town.addUnits(name, amount, unitType)          -- Adds additional units of unit type to the town and places them at a random residence.
--  [ ] ai.town.pause(town, [True, False])                -- Pauses / Unpauses all Units and Landmarks in a town.
--
--  Landmark Actions
--  [ ] ai.landmark.state(rect, state)           -- Changes the landmark state to the specified state
--  [ ] ai.landmark.kill(rect)                   -- Kills the landmark, displacing any Units connected to it.
--
--  Unit Actions
--  [X] ai.unit.state(unit, state)               -- Changes the unit state to the specified state
--  [ ] ai.unit.setHome(unit, landmark)          -- Sets what landmark this unit considers it's home.  Will be used to sleep when off-shift.
--  [A] ai.unit.addRoute(unit, route)            -- Adds the picked route to one of the units routes
--  [ ] ai.unit.addRoutes(unit, {routes})        -- Adds all of the routes contained in the routes list specified to the Unit.
--  [ ] ai.unit.changeHome(unit, rect)           -- Changes the unit's home position to the center of the selected rect.
--  [X] ai.unit.kill(unit)                       -- Kills the unit and removes all references from AI.
--  [X] ai.unit.remove(unit)                     -- Removes the unit from the game and all references to it.
--  [X] ai.unit.pause(unit)                      -- Puases a unit.  Pauses the unit and all updating.
--  [A] ai.unit.pickRoute(unit, route*, step*)   -- Starts unit down specified Route.  If no route is chosen, then will pick a random route that has been assigned to the unit.
--
--  Set Unit Types
--  [ ] ai.unit.villager(unit)                   -- Set unit as a Villager
--  [ ] ai.unit.militia(unit, unitTypeTransform) -- Set unit as a Militia
--  [ ] ai.unit.traveler(unit)                   -- Set unit as a Soldier
--  [ ] ai.unit.follower(unit, unitFollowing)    -- Set unit as a Follower, also need to specify the unit to follow.
--  [ ] ai.unit.child(unit)                      -- Set unit as a Child
--  [ ] ai.unit.custom(unit, {states})           -- Set unit as a custom type.  Will take on the states selected.
--
--
-----------
-- UNIT LOOPS
--
-- Main Unit Loops
--
--
--
-----------
-- STATES
--
--  Town States
--  [ ] auto        -- The town will automatically choose what state it should be in.
--  [ ] normal      -- *AUTO* The town is reporting everything is fine.
--  [ ] danger      -- *AUTO* The town is reporting that it is in danger.
--  [ ] pause       -- The town will tell all of it's residences to pause and wait.
--  [ ] gather      -- The town is reporting that everyone needs to gather in the town center
--  [ ] abandon     -- The town is reporting that everyone should Abandon the Town.
--
--  Landmark States
--  [ ] auto        -- The Landmark will automatically choose what state to be in.
--  [ ] normal      -- *AUTO* The Landmark is not reporting anything wierd.
--  [ ] danger      -- *AUTO* The Landmark is reporting danger
--  [ ] off         -- The Landmark is turned off and won't influence any behavior.
--
--  Unit States Available
--  [ ] auto        -- Unit will automatically choose what state to be in.
--  [ ] relax       -- Unit will stay where it's at and maybe run some specific animations.
--  [X] move        -- Unit will move around to a different spot inside it's current town.
--  [X] returnHome  -- Unit will move back to it's home position.
--  [ ] travel      -- Unit will travel to a new town.
--  [ ] gather      -- Unit will move to the Town gathering spot, pick a random spot to stand in.
--  [ ] sleep       -- Unit will look for a residence to sleep in for the night.
--  [ ] patrol      -- Unit will patrol around the town.  Looking for enemies to attack during his shift.
--  [ ] defend      -- Unit will defend the town until all threats have been eliminated.
--  [ ] guard       -- Unit will stand in a position and will guard it always during his shift.
--  [ ] attack      -- Unit will attack the specified town.
--  [ ] follow      -- Unit will follow it's attached unit
--  [ ] flee        -- Unit will try to run away. (Either to nearest safehouse, or will keep running to landmarks in town if no safehouses)
--  [ ] arm         -- Unit will try to find a barracks and arm himself to fight.
--
--  Unit States Transient
--  [X] moving          -- Unit is currently moving along a route.
--  [X] returningHome   -- Unit is currently returning home.
--
--
-----------
-- TYPES
--
--  Landmark Types (Each landmark can be multiple types)
--  [ ] residence   -- This landmark will allow Units to sleep in it.
--  [ ] safehouse   -- This landmark will allow Units to Hide in it when Fleeing from Danger.
--  [ ] barracks    -- This landmark can house soldiers to be deployed if the town is under attack.
--  [ ] gathering   -- This landmark is used to gather get the Units to gather together.
--
--  Route Types (Each route can only be one type)
--  [ ] inTown      -- This route will take units to other points in it's town.
--  [ ] outOfTown   -- This route will take a unit to a new town.
--
--  Unit Types (Each unit can only be one type at a time)
--  [X] villager    -- Ordinary villager.  Will go about business, will always run away, and never fight.  Slows down when hurt, won't leave town.
--          {relax, move, gather, sleep, flee}
--
--  [ ] militia     -- Appears as an ordinary villager but if town is in danger and contains a barracks, go to it and transform into a milita and fight.
--          {relax, move, gather, sleep, arm}
--
--  [ ] soldier     -- protects the town, never leaves the town unless told to attack another town.  Will always fight when under attack.
--          {relax, move, gather, sleep, guard, patrol, defend, attack}
--
--  [ ] traveler    -- Will go about business, will always run away, and never fight.  Slows down when hurt, will travel to other towns.
--          {relax, move, sleep, travel}
--
--  [ ] follower    -- Will always follow it's lead unit. (Good for pack mules, that type of thing)  If lead unit dies, will flee to it's town and become a villager.
--          {follow}
--
--  [ ] child       -- Will play during the day, or sight see.
--          {move, sleep, play}
--
--  [ ] custom      -- No states will be added to this unit.  Will need to manually set up what unit will do.
--
--
-----------
-- SHIFTS
--
--  [ ] day     -- Units will be awake and active during the day.
--  [ ] night   -- Units will be awake and active during the night.
--  [ ] all     -- Units will be awake and active always.
